//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giusti.Template.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Giusti.Template.Model.Resource.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Acao é obrigatório.
        /// </summary>
        internal static string Log_Acao {
            get {
                return ResourceManager.GetString("Log_Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo Acao excedeu o limite.
        /// </summary>
        internal static string Log_Acao_Tamanho {
            get {
                return ResourceManager.GetString("Log_Acao_Tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo DataInclusao é obrigatório.
        /// </summary>
        internal static string Log_DataInclusao {
            get {
                return ResourceManager.GetString("Log_DataInclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Funcionalidade é obrigatório.
        /// </summary>
        internal static string Log_Funcionalidade {
            get {
                return ResourceManager.GetString("Log_Funcionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo Funcionalidade excedeu o limite.
        /// </summary>
        internal static string Log_Funcionalidade_Tamanho {
            get {
                return ResourceManager.GetString("Log_Funcionalidade_Tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo IpMaquina é obrigatório.
        /// </summary>
        internal static string Log_IpMaquina {
            get {
                return ResourceManager.GetString("Log_IpMaquina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo IpMaquina excedeu o limite.
        /// </summary>
        internal static string Log_IpMaquina_Tamanho {
            get {
                return ResourceManager.GetString("Log_IpMaquina_Tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo LogId é obrigatório.
        /// </summary>
        internal static string Log_LogId {
            get {
                return ResourceManager.GetString("Log_LogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo OrigemAcesso é obrigatório.
        /// </summary>
        internal static string Log_OrigemAcesso {
            get {
                return ResourceManager.GetString("Log_OrigemAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo OrigemAcesso excedeu o limite.
        /// </summary>
        internal static string Log_OrigemAcesso_Tamanho {
            get {
                return ResourceManager.GetString("Log_OrigemAcesso_Tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo RegistroId é obrigatório.
        /// </summary>
        internal static string Log_RegistroId {
            get {
                return ResourceManager.GetString("Log_RegistroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo UsuarioId é obrigatório.
        /// </summary>
        internal static string Log_UsuarioId {
            get {
                return ResourceManager.GetString("Log_UsuarioId", resourceCulture);
            }
        }
    }
}
